#!/bin/sh
#
# Updates the version code

cd "$(dirname "$0")"
cd "$(git rev-parse --show-toplevel)"

version=$(git describe --tags --long --match "v*" | sed 's:v\(.*\)-\(.*\)-.*:\1.\2:')
short_version=$(git describe --tags --long --match "v*" | sed 's:v\([^-]*\).*:\1:')

sed -e "s/@VERSION@/$version/" Source/Properties/AssemblyInfo.in > tmp
cmp -s Source/Properties/AssemblyInfo.cs tmp || cp tmp Source/Properties/AssemblyInfo.cs

sed -e "s/@VERSION@/$short_version/" ProceduralParts.version.in > tmp
cmp -s ProceduralParts.version tmp || cp tmp ProceduralParts.version

rm tmp